### ISSUE TITLE
rse shell fails without ipython

### ISSUE THREAD

**Issue by untzag** [rseng/rse#50]
* Research Software Encyclopedia version: 0.0.30
* Python version:  3.9.0
* Operating System: Debian 10

### Description

`rse shell` fails when ipython is not installed.
No module IPython.
In my opinion this should fall back to another shell if IPython isn't found.
IPython is not (and should not be, in my opinion) a dependency of rse.

### What I Did

```bash
$ rse shell
INFO:rse.main:Database: filesystem
Traceback (most recent call last):
  File "/home/blaise/miniconda3/envs/rse/bin/rse", line 8, in <module>
    sys.exit(main())
  File "/home/blaise/miniconda3/envs/rse/lib/python3.9/site-packages/rse/client/__init__.py", line 477, in main
    main(args=args, extra=extra)
  File "/home/blaise/miniconda3/envs/rse/lib/python3.9/site-packages/rse/client/shell.py", line 23, in main
    return lookup[shell](args)
  File "/home/blaise/miniconda3/envs/rse/lib/python3.9/site-packages/rse/client/shell.py", line 35, in ipython
    from IPython import embed
ModuleNotFoundError: No module named 'IPython'
```

**Comment by vsoch** [comment]
Yes you are right, it should fallback! I'll open a PR soon with a fix.

**Comment by untzag** [comment]
humble suggestion: consider using `sys.executable`---this will work well even if your users are using strange environments
