### ISSUE TITLE
TypeError during `rse export` but still got "Export is complete!"

### ISSUE THREAD

**Issue by NickleDave** [rseng/rse#72]
* Research Software Encyclopedia version: 0.0.42
* Python version: 3.10.5
* Operating System: Ubuntu (Pop!-OS 22.04 LTS)

### Description

I was trying to `export` a site, to understand the command, as discussed in #71.

```
rse export --type static-web docs/ 
```

The contents of my directory are from running 
```
rse init .
rse import --type google-sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vTsPmEWUg8Tr1ZoYTcQ0kTdsCrVskQveSuwfdEHaktHtQG693O4DHQrZotoFd5dXCLAciykAYNf-RSz/pub?gid=0&single=true&output=csv" 
```
as in the `import` command docs: 

Then I did the 
```
rse export --type static-web docs/ 
```
and I got an "export complete" but there was a `TypeError` right before that (full traceback below).  
Not clear if there's something I'm doing wrong.

The site does appear to have been generated:
```
$ ls docs
api  criteria  data.json  index.html  repository  search  static  taxonomy
```

From squinting menacingly at the traceback, my guess is what's happening here is that the parser can't parse one of the sources that is not a GitHub or GitLab link?

### What I Did

```
$ rse export --type static-web docs/ 
Server initialized for gevent.
INFO:engineio.server:Server initialized for gevent.
Starting export for http://127.0.0.1:5000
Research Software Encyclopedia: running on http://127.0.0.1:5000
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:53] "HEAD / HTTP/1.1" 200 118 0.032824
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:53] "GET / HTTP/1.1" 200 4451 0.007007
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:53] "GET /repository/github/nwolek/audiomoth-scripts/annotate-criteria HTTP/1.1" 200 6959 0.134137
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/github/nwolek/audiomoth-scripts/annotate-taxonomy HTTP/1.1" 200 18818 0.100137
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/github/nwolek/audiomoth-scripts HTTP/1.1" 200 1890 0.002798
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/github/ChristianBergler/ANIMAL-SPOT/annotate-criteria HTTP/1.1" 200 7014 0.002462
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/github/ChristianBergler/ANIMAL-SPOT/annotate-taxonomy HTTP/1.1" 200 18830 0.003664
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/github/ChristianBergler/ANIMAL-SPOT HTTP/1.1" 200 1730 0.002515
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/github/patriceguyot/Acoustic_Indices/annotate-criteria HTTP/1.1" 200 6912 0.002571
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/github/patriceguyot/Acoustic_Indices/annotate-taxonomy HTTP/1.1" 200 18833 0.002451
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/github/patriceguyot/Acoustic_Indices HTTP/1.1" 200 1687 0.001672
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-adobe-com/products/audition-html/annotate-criteria HTTP/1.1" 200 6868 0.001764
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-adobe-com/products/audition-html/annotate-taxonomy HTTP/1.1" 200 18832 0.001930
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/www-adobe-com/products/audition-html HTTP/1.1" 200 865 0.000983
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/soundanalysis-wp-st-andrews-ac-uk/annotate-criteria HTTP/1.1" 200 6888 0.001135
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/soundanalysis-wp-st-andrews-ac-uk/annotate-taxonomy HTTP/1.1" 200 18825 0.001212
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/soundanalysis-wp-st-andrews-ac-uk HTTP/1.1" 200 976 0.000650
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-audacityteam-org/download/annotate-criteria HTTP/1.1" 200 6892 0.000749
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-audacityteam-org/download/annotate-taxonomy HTTP/1.1" 200 18813 0.000917
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/www-audacityteam-org/download HTTP/1.1" 200 994 0.000580
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/datadryad-org/stash/dataset/doi-10-5061/dryad-221mq23/annotate-criteria HTTP/1.1" 200 7022 0.000706
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/datadryad-org/stash/dataset/doi-10-5061/dryad-221mq23/annotate-taxonomy HTTP/1.1" 200 18883 0.000949
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/datadryad-org/stash/dataset/doi-10-5061/dryad-221mq23 HTTP/1.1" 200 1153 0.000638
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-titley-scientific-com/us/anabat-insight-html/annotate-criteria HTTP/1.1" 200 6951 0.000690
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/www-titley-scientific-com/us/anabat-insight-html/annotate-taxonomy HTTP/1.1" 200 18868 0.000914
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/www-titley-scientific-com/us/anabat-insight-html HTTP/1.1" 200 1278 0.000583
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/arbimon-rfcx-org/annotate-criteria HTTP/1.1" 200 6819 0.000666
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /repository/custom/arbimon-rfcx-org/annotate-taxonomy HTTP/1.1" 200 18774 0.000902
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/custom/arbimon-rfcx-org HTTP/1.1" 200 1188 0.000566
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api HTTP/1.1" 200 478 0.000591
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos HTTP/1.1" 200 2187 0.000873
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/parser/github HTTP/1.1" 200 749 0.000682
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/repos/parser/gitlab HTTP/1.1" 200 110 0.000451
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/taxonomy HTTP/1.1" 200 7885 0.000448
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /api/criteria HTTP/1.1" 200 1018 0.000379
ERROR:rse.app.server:Exception on /search [GET]
Traceback (most recent call last):
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/app/views/main.py", line 81, in search
    url = RSE_HOST + RSE_URL_PREFIX or flask.request.host_url + RSE_URL_PREFIX
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /search HTTP/1.1" 500 401 0.001437
Issue parsing http://127.0.0.1:5000/search
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /criteria HTTP/1.1" 200 2936 0.005845
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-08-21 17:52:54] "GET /taxonomy HTTP/1.1" 200 4440 0.012862
Generating data export
Export is complete!
```

**Comment by vsoch** [comment]
@NickleDave I think you are following the wrong docs - you want to export jekyll-web.  The static-web is from flask and you won't have the requirements installed by default. In case you don't have the previous link handy, the instruction is here https://github.com/rseng/rse-jekyll-web/#create-the-web.

**Comment by NickleDave** [comment]
Ah I see! My bad

Would it be worth checking if `flask` is installed and failing loudly?

**Comment by vsoch** [comment]
From the above you do have flask installed, but you ran an export command that expects a prefix defined (but it was not).

**Comment by vsoch** [comment]
Will have a PR with some tweaks soon.

**Comment by vsoch** [comment]
Fixed with https://github.com/rseng/rse/pull/75
