### ISSUE TITLE
"'Logger' object has no attribute 'exit'" from `rse import`

### ISSUE THREAD

**Issue by NickleDave** [rseng/rse#73]
* Research Software Encyclopedia version: 0.0.42
* Python version: 3.10.5
* Operating System: Ubuntu (Pop!-OS 22.04 LTS)

### Description

I am trying to run `rse import` on a copy of the original spreadsheet that the example in the docs is copied from.  
To do so, in the copy I changed the first two column titles to "Title" and "Url" (to match the example), and then I published to get a link as explained in the docs for the import command.  
I then ran the command with the published url (below) for the copy of the spreadsheet.  
I hit two errors: the first, because paste inserts backslashes that break the link; the second, because `rse` is not happy with one of the column titles.
The only reason the first matter errors is because it made it more obvious that there's some issue with the Logger that's preventing the full traceback from the second error getting logged -- i.e. I can't see what required field is missing.

### What I Did
error 1 (because of extra slashes inserted when pasting
```
$ rse import --type google-sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vQkPsu14BG0bErrY0thXymfS55be0spEVX_WpWm2Yy3We8swMO0sIb3iD4Sg-i1lWnxSsiiN5JmWAD-/pub\?gid\=0\&single\=true\&output\=csv"
Traceback (most recent call last):
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/bin/rse", line 8, in <module>
    sys.exit(main())
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/client/__init__.py", line 519, in main
    main(args=args, extra=extra)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/client/imp.py", line 24, in main
    results = importer.scrape(extra)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/main/scrapers/googlesheet.py", line 51, in scrape
    bot.exit(f"Issue parsing {url}: {response.text}")
AttributeError: 'Logger' object has no attribute 'exit'

```

error 2 (because of some {field} I'm missing in the spreadsheet)
```
$ rse import --type google-sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vQkPsu14BG0bErrY0thXymfS55be0spEVX_WpWm2Yy3We8swMO0sIb3iD4Sg-i1lWnxSsiiN5JmWAD-/pub?gid=0&single=true&output=csv" 
Traceback (most recent call last):
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/bin/rse", line 8, in <module>
    sys.exit(main())
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/client/__init__.py", line 519, in main
    main(args=args, extra=extra)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/client/imp.py", line 24, in main
    results = importer.scrape(extra)
  File "/home/pimienta/Documents/repos/coding/opensci/bioacoustics/bioacoustics-software/.venv/lib/python3.10/site-packages/rse/main/scrapers/googlesheet.py", line 63, in scrape
    bot.exit(f"Sheet {url} is missing required field {required}.")
AttributeError: 'Logger' object has no attribute 'exit'
```

**Comment by vsoch** [comment]
The logger missing exit is a bug (we can either add or change to sys.exit) but the error message (would have been) correct - the sheet is required to have a minimum set of fields as outlined in the docs.

**Comment by vsoch** [comment]
Fixed with https://github.com/rseng/rse/pull/75
